version: '3.8'

services:
  ngrok:
    build: .
    container_name: lyra_ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_SUBDOMAIN_INGEST=${NGROK_SUBDOMAIN_INGEST:-lyra-ingest}
      - NGROK_SUBDOMAIN_DASH=${NGROK_SUBDOMAIN_DASH:-lyra-dash}
      - NGROK_SUBDOMAIN_METRICS=${NGROK_SUBDOMAIN_METRICS:-lyra-metrics}
      - NGROK_SUBDOMAIN_INSPECT=${NGROK_SUBDOMAIN_INSPECT:-lyra-inspect}
    ports:
      - "4040:4040"  # Inspector
      - "8081:8081"  # Ingest Gateway
      - "8000:8000"  # Dashboard
      - "3000:3000"  # Grafana
      - "8086:8086"  # Hummingbot
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lyra_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "manus_verification.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  lyra_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
