version: "3"
authtoken: ${NGROK_AUTHTOKEN}
region: ap  # Asia-Pacific for 133ms latency
log_level: info
log_format: json
log: /app/logs/ngrok.log

tunnels:
  ingest:
    proto: http
    addr: localhost:8081
    hostname: ${NGROK_SUBDOMAIN_INGEST}.ngrok.app
    inspect: true
    metadata: '{"service": "ingest_gateway", "mode": "spot_monitoring"}'
  
  dashboard:
    proto: http
    addr: localhost:8000
    hostname: ${NGROK_SUBDOMAIN_DASH}.ngrok.app
    inspect: true
    metadata: '{"service": "lyra_dashboard", "mode": "monitoring"}'
  
  grafana:
    proto: http
    addr: localhost:3000
    hostname: ${NGROK_SUBDOMAIN_METRICS}.ngrok.app
    inspect: true
    metadata: '{"service": "grafana_metrics", "mode": "analytics"}'
  
  inspector:
    proto: http
    addr: localhost:4040
    hostname: ${NGROK_SUBDOMAIN_INSPECT}.ngrok.app
    inspect: false
    metadata: '{"service": "traffic_inspector", "mode": "audit"}'

web_addr: localhost:4040
